{ pkgs }:
{
  enable = true;
  onActivation.cleanup = "uninstall";
  taps = [
    "homebrew/bundle"
    "homebrew/cask-fonts"
    "jandedobbeleer/oh-my-posh"
    "mediosz/tap"
    "nikitabobko/tap"
    "oven-sh/bun"
  ];
  brews = [
    "berkeley-db"
    "libtiff"
    "gdk-pixbuf"
    "git"
    "harfbuzz"
    "librsvg"
    "openjdk"
    "maven"
    "nvm"
    "pipx"
    "pnpm"
    "postgresql@14"
    "pyenv"
    "python@3.10"
    "python@3.11"
    "python@3.12"
    "terraformer"
    "tfenv"
    "tmux"
    "zsh"
    "zsh-syntax-highlighting"
    "oven-sh/bun/bun"
  ];
  casks = [
    "1password"
    "aerospace"
    "arc"
    "bettertouchtool"
    "canva"
    "dbeaver-community"
    "devpod"
    "firefox"
    "font-fira-code"
    "ghostty"
    "gimp"
    "google-chrome"
    "imageoptim"
    "insomnia"
    "karabiner-elements"
    "keepassxc"
    "libreoffice"
    "nordvpn"
    "obsidian"
    "raycast"
    "spotify"
    "stretchly"
    "vlc"
    "whatsapp"
    "zoom"
  ];
}
